<?php

include_once('drupal_church_entityreference_autocomplete.inc');

function drupal_church_menu() {
  $items = array();

  $items['admin/church'] = array(
    'title' => 'Church',
    'description' => 'Church Settings',
    //TODO change access arguments
    'access arguments' => array(TRUE),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/church/configure'] = array(
    'title' => 'Configure Church Settings',
    //TODO change access arguments
    'access arguments' => array(TRUE),
    'weight' => 100,
  );

  //TODO remove before GOLIVE
  $items['admin/church/test'] = array(
    'title' => 'Test',
    'page callback' => 'drupal_church_test',
    'access arguments' => array(TRUE),
    'weight' => 100,
    'type' => MENU_NORMAL_ITEM,
  );


  //entityreference_autocomplete (era)
  $items['admin/church/autocomplete/%/%drupal_church_era_column/%drupal_church_era_bundles'] = array(
    'title' => 'Entity Reference Element autocomplete callback',
    'page callback' => 'drupal_church_era_callback',
    'page arguments' => array(3, 4, 5),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function drupal_church_test() {
  print 'HI';

//__create_inge_family();
}

//Auto creation of a few users
function __create_inge_family() {

  //DAD
  $p->is_new = TRUE;
  $p->type = 'member';
  $p->uid = 1;
  $p->field_person_gender['und'][0]['value'] = 'male';
  $p->field_name['und'][0]['given'] = 'Andrew';
  $p->field_name['und'][0]['middle'] = 'Vaiden';
  $p->field_name['und'][0]['family'] = 'Inge';

  church_people_save($p);

  //MOM
  unset($p);
  $p->is_new = TRUE;
  $p->type = 'member';
  $p->uid = 1;
  $p->field_person_gender['und'][0]['value'] = 'female';
  $p->field_name['und'][0]['given'] = 'Arteve';
  $p->field_name['und'][0]['middle'] = '';
  $p->field_name['und'][0]['family'] = 'Inge';

  church_people_save($p);

  //Sara
  unset($p);
  $p->is_new = TRUE;
  $p->type = 'member';
  $p->uid = 1;
  $p->field_person_gender['und'][0]['value'] = 'female';
  $p->field_name['und'][0]['given'] = 'Sara';
  $p->field_name['und'][0]['middle'] = 'Arteve';
  $p->field_name['und'][0]['family'] = 'Inge';

  church_people_save($p);

  //Steve
  unset($p);
  $p->is_new = TRUE;
  $p->type = 'member';
  $p->uid = 1;
  $p->field_person_gender['und'][0]['value'] = 'male';
  $p->field_name['und'][0]['given'] = 'Steven';
  $p->field_name['und'][0]['middle'] = 'Arthur';
  $p->field_name['und'][0]['family'] = 'Inge';

  church_people_save($p);

  //Pete
  unset($p);
  $p->is_new = TRUE;
  $p->type = 'member';
  $p->uid = 1;
  $p->field_person_gender['und'][0]['value'] = 'male';
  $p->field_name['und'][0]['given'] = 'Pete';
  $p->field_name['und'][0]['middle'] = 'Andrew';
  $p->field_name['und'][0]['family'] = 'Inge';

  church_people_save($p);

  //Pam
  unset($p);
  $p->is_new = TRUE;
  $p->type = 'member';
  $p->uid = 1;
  $p->field_person_gender['und'][0]['value'] = 'female';
  $p->field_name['und'][0]['given'] = 'Pam';
  $p->field_name['und'][0]['middle'] = '';
  $p->field_name['und'][0]['family'] = 'Inge';

  church_people_save($p);

  //Brandon
  unset($p);
  $p->is_new = TRUE;
  $p->type = 'member';
  $p->uid = 1;
  $p->field_person_gender['und'][0]['value'] = 'male';
  $p->field_name['und'][0]['given'] = 'Brandon';
  $p->field_name['und'][0]['middle'] = '';
  $p->field_name['und'][0]['family'] = 'Lynn';

  church_people_save($p);

  //Carrie
  unset($p);
  $p->is_new = TRUE;
  $p->type = 'member';
  $p->uid = 1;
  $p->field_person_gender['und'][0]['value'] = 'female';
  $p->field_name['und'][0]['given'] = 'Carrie';
  $p->field_name['und'][0]['middle'] = '';
  $p->field_name['und'][0]['family'] = 'Inge';

  church_people_save($p);

  //Vaiden
  unset($p);
  $p->is_new = TRUE;
  $p->type = 'member';
  $p->uid = 1;
  $p->field_person_gender['und'][0]['value'] = 'male';
  $p->field_name['und'][0]['given'] = 'Vaiden';
  $p->field_name['und'][0]['middle'] = 'James';
  $p->field_name['und'][0]['family'] = 'Inge';

  church_people_save($p);

  //Bill
  unset($p);
  $p->is_new = TRUE;
  $p->type = 'member';
  $p->uid = 1;
  $p->field_person_gender['und'][0]['value'] = 'male';
  $p->field_name['und'][0]['given'] = 'Bill';
  $p->field_name['und'][0]['middle'] = '';
  $p->field_name['und'][0]['family'] = 'Hedrick';

  church_people_save($p);

  //Ricky
  unset($p);
  $p->is_new = TRUE;
  $p->type = 'member';
  $p->uid = 1;
  $p->field_person_gender['und'][0]['value'] = 'male';
  $p->field_name['und'][0]['given'] = 'Ricky';
  $p->field_name['und'][0]['middle'] = '';
  $p->field_name['und'][0]['family'] = 'Lynn';

  church_people_save($p);

  //Adam
  unset($p);
  $p->is_new = TRUE;
  $p->type = 'member';
  $p->uid = 1;
  $p->field_person_gender['und'][0]['value'] = 'male';
  $p->field_name['und'][0]['given'] = 'Adam';
  $p->field_name['und'][0]['middle'] = '';
  $p->field_name['und'][0]['family'] = 'Lynn';

  church_people_save($p);
}