<?php

function drupal_church_menu() {
  $items = array();

  $items['admin/church'] = array(
    'title' => 'Church',
    'description' => 'Church Settings',
    'access arguments' => array(TRUE),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/church/configure'] = array(
    'title' => 'Configure Church Settings',
    'access arguments' => array(TRUE),
    'weight' => 100,
  );

  return $items;
}